development:
  host: 127.0.0.1
  database: markdown_manual_devel
  username: markdown_manual_devel
  password: ypGLLyssl

test:
  host: 127.0.0.1
  database: markdown_manual_test
  username: markdown_manual_test
  password: ypGLLyssl

production:
  host: 127.0.0.1
  database: markdown_manual_production
  username: markdown_manual_production
  password: <?=sha1(SECRET_TOKEN."Very_Sophisticated_Production_Password_Hiding")?>
