production:
  server: "ntvage.opalstacked.com"
  user: "ntvage"
  home_dir: "/home/{{user}}"
  env: "PATH={{home_dir}}/bin:$PATH"
  url: http://markdown.plovarna.cz/
  directory: "{{home_dir}}/apps/markdown_manual/"
  deploy_repository: "{{user}}@{{server}}:repos/markdown_manual.git"
  before_deploy:
  - "@local composer update"
  - "@local bower update"
  - "@local gulp"
  rsync:
  - "vendor"
  - "public/dist"
  after_deploy: "" # We don't need to run ./scripts/migrate - database is not in usage

# vim: set et:
