production:
  server: "ntvage.webfactional.com"
  user: "ntvage"
  url: http://markdown.plovarna.cz/
  directory: "/home/ntvage/webapps/markdown_manual/"
  deploy_repository: "ntvage@ntvage.webfactional.com:repos/markdown_manual.git"
  before_deploy:
  - "@local composer update"
  - "@local bower update"
  - "@local gulp"
  rsync:
  - "vendor"
  - "public/dist"
  after_deploy: "" # We don't need to run ./scripts/migrate - database is not in usage

# vim: set et:
