# Here is the list of languages used in your application.
# The first one is the default language. The front page is beeing served in the default language.

cs:
  LANG: cs_CZ.UTF-8

en:
  LANG: en_US.UTF-8
